title: Ruoyu
tagline: Time, truth, and hearts.
description: >-
  Welcome to my personal site. Glad to have you here.
url: https://www.ruoyu.xyz
baseurl: "" # the subpath of the site, e.g. /blog
lang: en-SG
logo: /assets/images/logo/logo.png

author: Ruoyu

# post settings
navigation_categories:
  -
    name: Blog
    path: /blog/
  -
    name: Projects
    path: /projects/
  -
    name: About
    path: /about/

hide_info: false
hide_author: false
hide_author_twitter: false
hide_date: false
hide_last_modified_at: false
hide_tags: false

twitter:
  username: ZhongRuoyu
  card: summary_large_image
social:
  name: Ruoyu
  links:
    - https://twitter.com/ZhongRuoyu
    - https://github.com/ZhongRuoyu

webmaster_verifications:
  google: kBhDIxREI8tuCvsoezLc7T4lOF0V5bP_8TaLIozGRMs
google_analytics: UA-167948296-1

permalink: /:categories/:year-:month/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
      image: /assets/images/default-card.png
  -
    scope:
      path: "_posts"
    values:
      layout: post
      author: Ruoyu
      hide_author_twitter: true

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
